global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus' 
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'Spring Boot'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['spring:8081']
        labels:
          application: "ticketing"
    tls_config:
      insecure_skip_verify: true

        