{
 "title": "ServerCalls",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Spring Observability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error traces 400|404|500",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "limit": 20,
     "query": "{ span.status = \"400\" || span.status = \"404\" || span.status = \"500\" }"
    }
   ]
  },
  {
   "title": "Authorization Traces 401|403",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "limit": 20,
     "query": "{ span.status = \"401\" || span.status = \"403\" }"
    }
   ]
  },
  {
   "title": "Success Traces 20x",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "limit": 20,
     "query": "{ span.status >= \"200\" AND span.status < \"300\" }"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Postgres",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"postgres\"}"
    }
   ]
  },
  {
   "title": "Spring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"spring\"}"
    }
   ]
  },
  {
   "title": "Keycloak",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"keycloak\"}"
    }
   ]
  },
  {
   "title": "Frequency of a method",
   "type": "timeseries",
   "description": "Describe the invocation frequency of all the methods.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(method_observed_seconds_count[$__interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Total calls to a URI",
   "type": "piechart",
   "description": "It's the sum of all the calls executed to a URI. (Excluding /actuator/prometheus)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{uri!=\"/actuator/prometheus\"}",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}